### ISSUE TITLE
Respect image sequence frame rate, when available

### ISSUE THREAD

**Issue by adamwilt** [videovillage/Screen-Issues#31]
When an image sequence has a frame rate embedded in its metadata, use that frame rate instead of using Screen's Default Sequence Framerate.

With Screen's Default Sequence Framerate set to 23.98 fps, this is the Basic Info for a sequence of DPX frames scanned from film:

![DPX-basicInfo](https://user-images.githubusercontent.com/2841957/77131284-6a18f000-6a18-11ea-8050-60734c155334.png)

Yet the film was scanned at 25 fps, and this was recorded in the DPX metadata:

![DPX-metadata](https://user-images.githubusercontent.com/2841957/77131332-96cd0780-6a18-11ea-932e-c07d06e1d3e6.png)

An exported MP4 of the sequence played at 23.98 fps. I re-rendered after setting Default Sequence Framerate for 25 fps, but it would be nice if Screen used the frame rate in the metadata automatically.

OK, that doesn't handle things like high-speed shooting scanned with 24 fps metadata. Perhaps a warning of some sort, that "frame rate doesn't match metadata" or the like (the way Resolve warns that clip settings don't match timeline settings when you drag the first clip to a timeline), with an option to keep one or the other or even enter a new frame rate?

**Comment by gregcotten** [comment]
Screen definitely handles embedded frame rates when detected, but it seems this DPX framerate metadata key is not one of the ones we are looking for! I emailed you a Google Drive upload link - would you mind sending a single frame to me so I can verify it is fixed?

I also agree that an override framerate is in order so that you can change the playback framerate on the fly. In the Basic Info we should definitely add "(Inferred)" if the framerate had to be inferred by Screen.

**Comment by adamwilt** [comment]
> Screen definitely handles embedded frame rates when detected, but it seems this DPX framerate metadata key is not one of the ones we are looking for! I emailed you a Google Drive upload link - would you mind sending a single frame to me so I can verify it is fixed?

Done: the first frame, and a frame 320 frames later, just in case.

Thanks!
Adam Wilt
technical services
Vancouver WA USA (no, not that Vancouver, the other one)

**Comment by gregcotten** [comment]
Fixed and in next release!

**Comment by adamwilt** [comment]
:-)
