### ISSUE TITLE
A couple feature requests

### ISSUE THREAD

**Issue by ronarcadia** [videovillage/Screen-Issues#34]
Hello! Just a couple feature requests:

- optional title safe display

- an option to turn off side-scrolling (I'm constantly losing my spot in videos because of the apple magic mouse side-scrolling)

- would be nice if mouse cursor eventually goes invisible (over the app's viewer area) shortly after video starts playing

BTW, I'm on macos 10.4.6 on a 2017 iMac Pro. Using Screen version 1.1.10 (2296).

**Comment by gregcotten** [comment]
"an option to turn off side-scrolling (I'm constantly losing my spot in videos because of the apple magic mouse side-scrolling)"

The newest update of Screen (released today) adds support for disabling horizontal scrolling!

Definitely agree on the others. Overlays are coming soon - definitely can add an option for hiding the mouse cursor if the mouse is over the viewer area in windowed mode.

**Comment by ronarcadia** [comment]
Thanks very much!

I only bothered making requests because I love the app and use it every day.

So glad that to have it.

Cheers!

Ron

________________________________
